# Generated by Django 3.2 on 2023-12-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_review_author_title_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_author_title_unique',
        ),
    ]
